[project]
name = "icloud-contacts-downloader"
version = "0.1.0"
description = "A script for downloading contacts from iCloud"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyicloud>=2.0.1",
]
